services:
  db:
    image: postgres:16
    container_name: codeform-db
    environment:
      POSTGRES_USER: codeform
      POSTGRES_PASSWORD: codeform
      POSTGRES_DB: protocolo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
